class AppString {
  static String appname = "Salon Booking App",
      bestDocapp = "Best Salon\n Appointment App",
      welcome = "Welcome ",
      weAreExcuited = "We are happy to have you back",
      signupNow = "Signup now and start exploring all",
      email = "Email",
      emailHint = "Enter your email ",
      password = "Password",
      passwordHint = "Enter your password",
      fullName = "Full name",
      fullnameHint = "Enter your full name",
      confirmPassword = "Confirm password",
      login = "Login",
      signup = "Signup",
      search = "Search ",
      alreadyHaveAccount = "Already have an account !",
      hair = "Hair",
      nail = "Nail",
      makeup = "Makeup",
      spa = "Spa",
      facial = "Facial",
      eye = "Eye",
      dontHaveAccount = "Don't have an account";
}
